### ISSUE TITLE
this._getTileSize is not a function

### ISSUE THREAD

**Issue by ultimate-tester** [mWater/offline-leaflet-map#16]
Possibly the source for this plugin is outdated. I get an error when trying to calculate the amount of to be saved tiles using calculateNbTiles:

**this._getTileSize is not a function     offlinemap.js:2916:16**

I can not find this function in the source code, did it get renamed?

**Comment by ultimate-tester** [comment]
I worked around this problem by replacing line 2916 with the following:

`tileSize = this.getTileSize().x;`

This does not feel like an elegant solution though...

**Comment by grassick** [comment]
Which version of leaflet are you using? This was working with 0.7, perhaps the API has changed?

**Comment by ultimate-tester** [comment]
I'm using Leaflet 1.0.1. This is not the only bug I'm experiencing. While downloading tiles I get a lot of 404's which seem like tiles that don't even exist (x and y numbers are very high). Also I can not download the tiles directly from osm.org due to CORS so I cannot test it any further at the moment.. Perhaps I will create a pull request in the near feature.

**Comment by grassick** [comment]
I'm using     

```
mapquestUrl = 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png'
mapquestAttrib = 'Data, imagery and map information provided by MapQuest, OpenStreetMap and contributors.'
```

As my source and it has worked (at least in the past).

Thanks for the heads up re. Leaflet 1.0. I'll add a fix.

**Comment by grassick** [comment]
Ok, 0.2.0 is live and should work with both versions of leaflet. Thanks!
